server: 
  port: 80
spring:
  application: 
    name: tattooju
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: admin@123
    url: "jdbc:mysql://39.106.205.81:3306/tattooju_dev?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: admin
  redis:
    database: 0
    host: 39.106.205.81
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 300
      max-wait: -1
wechat:
  url: 
    appId: wxb18ce3e6d926910f
    appSecret: 7477ec5e523a572c3369e6d95c0b9151
token:
  verify:
    switch: false
    ttl: 30
  interceptor:
    exclude: 
      url: /**.html,/user/
fdfs:
  connect_timeout: 30
  network_timeout: 30
  charset: UTF-8
  tracker_server: 39.106.205.81:22122
  nginx:
    path: http://39.106.205.81:8888